spring.application.name=piyu-products
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/dev?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#If your MySql version 5 then use MySQL5Dialect

server.port=9600
# Enable spring data repos
spring.data.jpa.repositories.enabled=true
spring.jpa.show-sql=true

app.cors.allowed-origins=${ALLOWED_ORIGIN:http://localhost:5173}